[project]
name = "python-scaffold"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kohei Kumazawa", email = "48900989+dfc22@users.noreply.github.com" },
    { name = "Hodaka Ueda", email = "35979840+hodhodhod@users.noreply.github.com" }
]
dependencies = [
    "python-dotenv>=1.0.0",
    "pyhumps>=3.8.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.2.1",
]

[tool.rye.scripts]
clean = "find . ( -type d -name '__pycache__' -o -type f -name '*.log' -o -type d -name './.ruff_cache' -o -type d -name './.venv' -o -type d -name './logs' ) -exec rm -r {} ;"
execute = "rye run python3 script/__execute__.py"

[tool.hatch.build.targets.wheel]
packages = ["src", "script"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
target-version = "py311"

line-length = 120
select = ["ALL"]

unfixable = ["ERA001", "F401", "F841"]

ignore = ["ANN101", "ANN102", "TD", "D", "PGH003", "PGH004"]
