version: "3"

tasks:
  install:
    cmds:
      - brew install uv
      - brew install visual-studio-code
      - code --install-extension ms-python.python
      - code --install-extension ms-python.vscode-pylance
      - code --install-extension charliermarsh.ruff
      - code --install-extension tamasfe.even-better-toml
      - code --install-extension esbenp.prettier-vscode
      - code --install-extension streetsidesoftware.code-spell-checker
  init:
    cmds:
      - uv sync
      - uvx pre-commit install
  activate:
    cmds:
      - source .venv/bin/activate
  update:
    cmds:
      - uv sync -U
      - uvx pre-commit autoupdate

  create-init:
    internal: true

    status:
      - test -f {{.DIRECTORY}}/__init__.py
    cmds:
      - touch {{.DIRECTORY}}/__init__.py

  create-all-inits:
    vars:
      FIND_OPTIONS_GITIGNORE:
        sh: git status --ignored -s | grep '^!! src/.*/$' | sed 's/^!!/! -path/g; s/\/$//g' | tr '\n' ' '
      ALL_DIRS:
        sh: find src -type d {{.FIND_OPTIONS_GITIGNORE}}
    cmds:
      - for:
          var: ALL_DIRS
          as: DIR
        task: create-init
        vars:
          DIRECTORY: "{{.DIR}}"
  mkdir:
    cmds:
      - mkdir -p {{.DIR}}
      - task: create-all-inits
