version: "3"

tasks:
  install:
    cmds:
      - brew install uv
      - brew install visual-studio-code
      - code --install-extension ms-python.python
      - code --install-extension ms-python.vscode-pylance
      - code --install-extension charliermarsh.ruff
      - code --install-extension tamasfe.even-better-toml
      - code --install-extension esbenp.prettier-vscode
      - code --install-extension streetsidesoftware.code-spell-checker
  init:
    cmds:
      - uv sync
      - uvx pre-commit install
  activate:
    cmds:
      - source .venv/bin/activate
  update:
    cmds:
      - uv sync -U
      - uvx pre-commit autoupdate
