version: "3"

tasks:
  install:
    cmds:
      - brew install uv
      - brew install visual-studio-code
      - task: install-extension

  install-extension:
    vars:
      EXTENSIONS:
        sh: jq -r '.recommendations[]' .vscode/extensions.json
    cmds:
      - for:
          var: EXTENSIONS
          as: EXT
        cmd: code --install-extension {{.EXT}}
  init:
    cmds:
      - uv sync
      - uvx pre-commit install

  update:
    cmds:
      - brew update
      - brew upgrade uv
      - uv sync -U
      - uvx pre-commit autoupdate
      - brew upgrade visual-studio-code
      - code --update-extensions

  create-init:
    internal: true

    status:
      - test -f {{.DIRECTORY}}/__init__.py
    cmds:
      - touch {{.DIRECTORY}}/__init__.py

  create-all-inits:
    vars:
      FIND_OPTIONS_GITIGNORE:
        sh: git status --ignored -s | grep '^!! src/.*/$' | sed 's/^!!/! -path/g; s/\/$//g' | tr '\n' ' '
      ALL_DIRS:
        sh: find src -type d {{.FIND_OPTIONS_GITIGNORE}}
    cmds:
      - for:
          var: ALL_DIRS
          as: DIR
        task: create-init
        vars:
          DIRECTORY: "{{.DIR}}"
  mkdir:
    cmds:
      - mkdir -p {{.DIR}}
      - task: create-all-inits
